CREATE SEQUENCE account_sequence START 1 INCREMENT 50;
CREATE SEQUENCE email_data_sequence START 1 INCREMENT 50;
CREATE SEQUENCE phone_data_sequence START 1 INCREMENT 50;
CREATE SEQUENCE user_sequence START 1 INCREMENT 50;